### ISSUE TITLE
BB code or html in item_details

### ISSUE THREAD

**Issue by cunaedy** [cunaedy/Kemana-Directory#1]
(As asked in the forum)
Hello, is it possible to allow BBCode or some Html tags in Item_details? Also i have noticed bug with listing. If you Edit listing as admin your Sort points suddenly becomes to 0 (I think it something with "last update" because i believe it sends wrong date, and according to our points system its suddenly become 0 no matter how much pts you had before) PS. Thank you for making this system!

**Comment by cunaedy** [comment]
Hi,
1. Unfortunately no. I want to avoid XSS. But in the future release, I may add MarkDown???
2. I think you are correct. To fix the problem:

Remove the following line:
https://github.com/cunaedy/Kemana-Directory/blob/25359e47214d03777258217fba0b70f8a13e29fa/admin/listing_process.php#L189

And replace the following line:
https://github.com/cunaedy/Kemana-Directory/blob/25359e47214d03777258217fba0b70f8a13e29fa/admin/listing_process.php#L239

To this line:
https://github.com/cunaedy/Kemana-Directory/blob/1f3050f93e407084c0eb6ff565cf195ce9fb58eb/admin/listing_process.php#L238

**Comment by TavoVolfas** [comment]
Thank you! I believe it fix the bug. 

About HTML. Well people are used to know simple html tags like ` <b  <img` some formatting tags like color, size. 
Of course it would be amazing to have description editor something like in reddit or here. (Allowed most important tags, and formating even from copy/paste text)

To prevent XSS maybe we could just ignore other tags except our "whitelisted"?
and/or just replace <script> to `&lt;script&lt;` everywhere in user input? I don't know much about XSS so i could be wrong.

PS. Why BB code is disabled and what made you to decide it (just curious) ?

**Comment by cunaedy** [comment]
Hi,\
Unfortunately, preventing XSS is not that easy, eg, you can still do XSS by using:
* ```<a href="javascript:alert(1)">```
* ```<div onclick="alert(1)">```
* ```<img src="javascript:alert(1)">``` (doesn't actually work anymore in modern browsers)
* ```<div style="background-image: url(javascript:alert(1))">``` (doesn't work anymore)
Source: https://stackoverflow.com/questions/53427381/is-using-jquery-parsehtml-to-remove-script-tags-enough-to-prevent-xss-attacks

So, I think it's easier :stuck_out_tongue_winking_eye: to remove the HTML support all together, except for backend.

About BBCode. I removed it because my implementation of BBCode was flawed.

In the future, I may re-add BBCode or MarkDown, or simply use plain text....?
